a = input('Digite Algo ')
print(f'O tipo primitivo de{a} é', type(a))
print(f'só tem espaços ? {a.isspace()}')
print(f'é um Número ? {a.isnumeric()}')
print(f'é Alfabéfico? {a.isalpha()}')
print(f'o {a} é um alfanúmerico? {a.isalnum()}')
print(f'a palavra {a} esta somentes em letra maiúscolas? {a.isupper()}')
print(f'a palavras {a} esta somentes em letra minúsculas? {a.islower()}')
print(f'a palavras {a} esta capitalizada? {a.istitle()}')
